image:
  repository: sysintelligent/hello-app
  tag: 2.0.1

resources:
  limits:
    cpu: 50m
    memory: 20Mi

service:
  type: NodePort  # Options: NodePort, LoadBalancer, ClusterIP
  name: hello-app-nodeport
  port: 80
  targetPort: 8080
  nodePort: 30000

loadBalancer:
  enabled: true  # Set to true to create additional LoadBalancer service
  name: hello-app-lb
  port: 80
  targetPort: 8080

# Main service names
mainService:
  nodeport: hello-app-nodeport
  loadbalancer: hello-app

# Istio VirtualService configuration
virtualService:
  enabled: false  # Set to true to create VirtualService for Istio routing
  domain: c-3bc6feb.stage.kyma.ondemand.com  # Your cluster domain (discoverable via kubectl get configmap shoot-info -n kube-system -o jsonpath='{.data.domain}')
  hosts:
    - host: hello-app  # Subdomain prefix (will become hello-app.{domain})
      paths:
        - path: /
