{{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "ClusterIP") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mainService.nodeport }}
  namespace: hello-app
  labels:
    app: hello-app
    type: {{ .Values.service.type }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
{{- end }}
